### ISSUE TITLE
This breaks if there is a NaN in the array. Fix this, and the if statement a few lines above to handle such cases.

### ISSUE THREAD

**Issue by EchoBetaGlass** [industrial-optimization-group/pyRVEA#9]
https://github.com/industrial-optimization-group/pyRVEA/blob/6f6a7b9bbeb82d3216d2ffb9e7d544099b17f6b4/pyRVEA/Selection/APD_select.py#L80

**Comment by EchoBetaGlass** [comment]
replace with np.nanmin() perhaps

**Comment by amrzr** [comment]
for i in range(0, len(vectors.values)):
        sub_population_index = np.atleast_1d(
            np.squeeze(np.where(assigned_vectors == i))
        )
        sub_population_fitness = translated_fitness[sub_population_index]
        if len(sub_population_fitness > 0):
            # APD Calculation
            angles = theta[sub_population_index, i]
            angles = np.divide(angles, refV[i])  # This is correct.
            # You have done this calculation before. Check with fitness_norm
            # Remove this horrible line
            sub_pop_fitness_magnitude = np.sqrt(
                np.sum(np.power(sub_population_fitness, 2), axis=1)
            )
            apd = np.multiply(
                np.transpose(sub_pop_fitness_magnitude),
                (1 + np.dot(penalty_factor, angles)),
            )
            minidx = np.where(apd == np.nanmin(apd))
            if np.isnan(apd).all():
                continue
            selx = sub_population_index[minidx]
            if selection.shape[0] == 0:
                selection = np.hstack((selection, np.transpose(selx[0])))
            else:
                selection = np.vstack((selection, np.transpose(selx[0])))
    return selection.squeeze()

**Comment by EchoBetaGlass** [comment]
Fixed.
